server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
//C'est la configuration **SPA (Single Page Application)**. Sans elle, si quelqu'un tape directement 
`http://localhost:5173/dashboard` dans son navigateur, Nginx chercherait un fichier `dashboard.html`
 qui n'existe pas et retournerait une erreur 404.