version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Port de dev Vite
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000


  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db        # C'est l'hôte magique pour Docker
      - DB_PORT=5432
      - DB_NAME=vihdatacaredb
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=vihdatacaredb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
